[theme]
primaryColor = "#10b981"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
